// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Todo_screen_init(void)
{
    ui_Todo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Todo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Todo, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Todo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TodoTitle = lv_obj_create(ui_Todo);
    lv_obj_set_width(ui_TodoTitle, 320);
    lv_obj_set_height(ui_TodoTitle, 55);
    lv_obj_set_align(ui_TodoTitle, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_TodoTitle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TodoTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TodoTitle, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TodoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TodoTitle, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TodoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title = lv_label_create(ui_TodoTitle);
    lv_obj_set_width(ui_Title, 300);
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Title, 0);
    lv_obj_set_y(ui_Title, -10);
    lv_obj_set_align(ui_Title, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Title, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Title, "Notes Title ");
    lv_obj_set_style_text_color(ui_Title, lv_color_hex(0x757CF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Todo);
    lv_obj_set_width(ui_Panel5, 120);
    lv_obj_set_height(ui_Panel5, 25);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, 25);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xE7AB08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0xEA980A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Status, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Status, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Status, "Not Started");
    lv_obj_set_style_text_color(ui_Status, lv_color_hex(0xFFA600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Status, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Todo);
    lv_obj_set_width(ui_Panel6, 260);
    lv_obj_set_height(ui_Panel6, 75);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DueDateImage = lv_image_create(ui_Panel6);
    lv_image_set_src(ui_DueDateImage, &ui_img_1785934031);
    lv_obj_set_width(ui_DueDateImage, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_DueDateImage, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_DueDateImage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DueDateImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DueDateImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_DueDateImage, LV_IMAGE_ALIGN_LEFT_MID);

    ui_Label3 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 10);
    lv_obj_set_y(ui_Label3, -20);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Due Date:");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DueDate = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_DueDate, 180);
    lv_obj_set_height(ui_DueDate, 25);
    lv_obj_set_x(ui_DueDate, 10);
    lv_obj_set_y(ui_DueDate, 5);
    lv_obj_set_align(ui_DueDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DueDate, "Dec 31, 9999 23:59");
    lv_obj_set_style_text_color(ui_DueDate, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DueDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DueDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Details = lv_button_create(ui_Todo);
    lv_obj_set_width(ui_Details, 260);
    lv_obj_set_height(ui_Details, 35);
    lv_obj_set_x(ui_Details, 0);
    lv_obj_set_y(ui_Details, -25);
    lv_obj_set_align(ui_Details, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Details, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Details, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Details, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Details, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Details, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Details, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Details, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Details, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Details, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Details);
    lv_image_set_src(ui_Image4, &ui_img_2086523439);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image4, 40);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Details);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "VIEW DETAILS");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back2Chat2 = lv_button_create(ui_Todo);
    lv_obj_set_width(ui_Back2Chat2, 40);
    lv_obj_set_height(ui_Back2Chat2, 40);
    lv_obj_set_x(ui_Back2Chat2, 115);
    lv_obj_set_y(ui_Back2Chat2, -75);
    lv_obj_set_align(ui_Back2Chat2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back2Chat2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Back2Chat2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Back2Chat2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Back2Chat2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back2Chat2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Back2Chat2, &ui_img_chat_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Back2Chat2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Back2Chat2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Back2Chat2, lv_color_hex(0x62E6BD), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Back2Chat2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Back2Chat2, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Back2Chat2, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_offset_x(ui_Back2Chat2, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_offset_y(ui_Back2Chat2, 0, LV_PART_MAIN | LV_STATE_PRESSED);

}
