// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Play_Animation(lv_obj_t * TargetObject, int delay);
void Dots_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
lv_obj_t * ui_Splash;
lv_obj_t * ui_logo;
lv_obj_t * ui_dotp;
lv_obj_t * ui_dotg;
lv_obj_t * ui_dotb;
lv_obj_t * ui_text;


// SCREEN: ui_Record
void ui_Record_screen_init(void);
lv_obj_t * ui_Record;
void ui_event_Image12(lv_event_t * e);
lv_obj_t * ui_Image12;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Wifi;
lv_obj_t * ui_ServerConn;
lv_obj_t * ui_Settings;


// SCREEN: ui_Chat
void ui_Chat_screen_init(void);
lv_obj_t * ui_Chat;
lv_obj_t * ui_TextArea1;
void ui_event_RecordSmall(lv_event_t * e);
lv_obj_t * ui_RecordSmall;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_Settings2;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_ellipse_[3] = {&ui_img_ellipse_4_png, &ui_img_ellipse_5_png, &ui_img_ellipse_6_png};
const lv_image_dsc_t * ui_imgset_flexibility_2969792_[1] = {&ui_img_flexibility_12969792_1_png};
const lv_image_dsc_t * ui_imgset_microphone_0307974_[1] = {&ui_img_microphone_10307974_1_png};
const lv_image_dsc_t * ui_imgset_button[2] = {&ui_img_button1_png, &ui_img_button2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Play_Animation(lv_obj_t * TargetObject, int delay)
{

}
void Dots_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 50);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, -10);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 200);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 4);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 200);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Dots_Animation(ui_dotb, 600);
        Dots_Animation(ui_dotg, 550);
        Dots_Animation(ui_dotp, 500);
        _ui_screen_change(&ui_Record, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 2000, &ui_Record_screen_init);
    }
}
void ui_event_Image12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_Spinner1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Chat, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_Chat_screen_init);
    }
}
void ui_event_RecordSmall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_Spinner2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Spinner2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Splash_screen_init();
    ui_Record_screen_init();
    ui_Chat_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Splash);
}
