// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Play_Animation(lv_obj_t * TargetObject, int delay);
void Dots_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_dotp;
extern lv_obj_t * ui_dotg;
extern lv_obj_t * ui_dotb;
extern lv_obj_t * ui_text;
// SCREEN: ui_Record
void ui_Record_screen_init(void);
extern lv_obj_t * ui_Record;
void ui_event_Image12(lv_event_t * e);
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Spinner1;
void ui_event_Settings3(lv_event_t * e);
extern lv_obj_t * ui_Settings3;
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_ServerConn;
// SCREEN: ui_Chat
void ui_Chat_screen_init(void);
extern lv_obj_t * ui_Chat;
extern lv_obj_t * ui_TextArea1;
void ui_event_RecordSmall(lv_event_t * e);
extern lv_obj_t * ui_RecordSmall;
extern lv_obj_t * ui_Spinner2;
void ui_event_Settings2(lv_event_t * e);
extern lv_obj_t * ui_Settings2;
// SCREEN: ui_Setup
void ui_Setup_screen_init(void);
extern lv_obj_t * ui_Setup;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_SetupMessage;
void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
// SCREEN: ui_Email
void ui_Email_screen_init(void);
void ui_event_Email(lv_event_t * e);
extern lv_obj_t * ui_Email;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Subject;
extern lv_obj_t * ui_DateTime;
extern lv_obj_t * ui_MessageLabel;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_EmailMessage;
extern lv_obj_t * ui_ActionPanel;
extern lv_obj_t * ui_ActionLabel;
extern lv_obj_t * ui_ActionValue;
extern lv_obj_t * ui_ActionImage;
extern lv_obj_t * ui_SentimentPanel;
extern lv_obj_t * ui_SentimentLabel;
extern lv_obj_t * ui_SentimentValue;
extern lv_obj_t * ui_SentimentImage;
extern lv_obj_t * ui_PriorityPanel;
extern lv_obj_t * ui_PriorityLabel;
extern lv_obj_t * ui_PriorityValue;
extern lv_obj_t * ui_PriorityImage;
extern lv_obj_t * ui_LabelSuggested;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_SuggestedResponse;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_flexibility_12969792_1_png);    // assets/flexibility_12969792 1.png
LV_IMG_DECLARE(ui_img_ellipse_4_png);    // assets/Ellipse 4.png
LV_IMG_DECLARE(ui_img_ellipse_5_png);    // assets/Ellipse 5.png
LV_IMG_DECLARE(ui_img_ellipse_6_png);    // assets/Ellipse 6.png
LV_IMG_DECLARE(ui_img_workdot_png);    // assets/WorkDot.png
LV_IMG_DECLARE(ui_img_microphone_10307974_1_png);    // assets/microphone_10307974 1.png
LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_button1_1_png);    // assets/Button1_1.png
LV_IMG_DECLARE(ui_img_button1_png);    // assets/Button1.png
LV_IMG_DECLARE(ui_img_button2_1_png);    // assets/Button2_1.png
LV_IMG_DECLARE(ui_img_button2_png);    // assets/Button2.png
LV_IMG_DECLARE(ui_img_record_small_png);    // assets/Record_Small.png
LV_IMG_DECLARE(ui_img_172201545);    // assets/backward-solid 1.png
LV_IMG_DECLARE(ui_img_actionimage_png);    // assets/ActionImage.png
LV_IMG_DECLARE(ui_img_sentimentimage_png);    // assets/SentimentImage.png
LV_IMG_DECLARE(ui_img_priorityimage_png);    // assets/PriorityImage.png
LV_IMG_DECLARE(ui_img_chat_png);    // assets/Chat.png
LV_IMG_DECLARE(ui_img_chat_pressed_png);    // assets/Chat_Pressed.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
