// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Chat_screen_init(void)
{
    ui_Chat = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Chat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Chat);
    lv_obj_set_width(ui_TextArea1, 259);
    lv_obj_set_height(ui_TextArea1, 227);
    lv_obj_set_x(ui_TextArea1, 7);
    lv_obj_set_y(ui_TextArea1, 6);
    lv_textarea_set_max_length(ui_TextArea1, 5000);
    lv_textarea_set_placeholder_text(ui_TextArea1, "You : What is Hackathon?");
    lv_obj_remove_flag(ui_TextArea1, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags



    ui_RecordSmall = lv_image_create(ui_Chat);
    lv_image_set_src(ui_RecordSmall, &ui_img_record_small_png);
    lv_obj_set_width(ui_RecordSmall, LV_SIZE_CONTENT);   /// 58
    lv_obj_set_height(ui_RecordSmall, LV_SIZE_CONTENT);    /// 58
    lv_obj_set_x(ui_RecordSmall, 125);
    lv_obj_set_y(ui_RecordSmall, 74);
    lv_obj_set_align(ui_RecordSmall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecordSmall, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_RecordSmall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_RecordSmall, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_RecordSmall, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_RecordSmall, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_RecordSmall, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Spinner2 = lv_spinner_create(ui_Chat);
    //lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 70);
    lv_obj_set_height(ui_Spinner2, 70);
    lv_obj_set_x(ui_Spinner2, 126);
    lv_obj_set_y(ui_Spinner2, 74);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Settings2 = lv_button_create(ui_Chat);
    lv_obj_set_width(ui_Settings2, 50);
    lv_obj_set_height(ui_Settings2, 50);
    lv_obj_set_x(ui_Settings2, 133);
    lv_obj_set_y(ui_Settings2, -81);
    lv_obj_set_align(ui_Settings2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Settings2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Settings2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Settings2, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Settings2, &ui_img_vector_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Settings2, lv_color_hex(0x008397), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Settings2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings2, lv_color_hex(0x0A8386), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Settings2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Settings2, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_RecordSmall, ui_event_RecordSmall, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings2, ui_event_Settings2, LV_EVENT_ALL, NULL);

}
