// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Email_screen_init(void)
{
    ui_Email = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Email, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_style_bg_color(ui_Email, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Email, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Email);
    lv_obj_set_width(ui_Panel2, 320);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Subject = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Subject, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Subject, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Subject, 0);
    lv_obj_set_y(ui_Subject, -10);
    lv_obj_set_align(ui_Subject, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Subject, "Email Subject");
    lv_obj_set_style_text_color(ui_Subject, lv_color_hex(0x757CF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Subject, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Subject, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTime = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_DateTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateTime, 0);
    lv_obj_set_y(ui_DateTime, 10);
    lv_obj_set_align(ui_DateTime, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_DateTime, "DateTime");
    lv_obj_set_style_text_color(ui_DateTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MessageLabel = lv_label_create(ui_Email);
    lv_obj_set_width(ui_MessageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MessageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MessageLabel, -121);
    lv_obj_set_y(ui_MessageLabel, 56);
    lv_obj_set_align(ui_MessageLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_MessageLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_MessageLabel, "Message");
    lv_obj_set_style_text_color(ui_MessageLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MessageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MessageLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Email);
    lv_obj_set_width(ui_Panel3, 300);
    lv_obj_set_height(ui_Panel3, 70);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 75);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Panel3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmailMessage = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_EmailMessage, 290);
    lv_obj_set_height(ui_EmailMessage, 65);
    lv_obj_set_align(ui_EmailMessage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmailMessage,
                      "Thanks Manoj, I see the claims in the decrypted Jwt token but for some reason they are not mapped to the Principal, so this always fails.  \n\nAny idea why?\n\nYour response will be appreciated!\n\nFrom: Stephen Halter  ");
    lv_obj_set_style_text_color(ui_EmailMessage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EmailMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EmailMessage, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EmailMessage, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionPanel = lv_obj_create(ui_Email);
    lv_obj_remove_style_all(ui_ActionPanel);
    lv_obj_set_width(ui_ActionPanel, 108);
    lv_obj_set_height(ui_ActionPanel, 52);
    lv_obj_set_x(ui_ActionPanel, -92);
    lv_obj_set_y(ui_ActionPanel, 56);
    lv_obj_set_align(ui_ActionPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ActionPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ActionPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ActionPanel, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionLabel = lv_label_create(ui_ActionPanel);
    lv_obj_set_width(ui_ActionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ActionLabel, 10);
    lv_obj_set_y(ui_ActionLabel, -5);
    lv_obj_set_align(ui_ActionLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_ActionLabel, "Action");
    lv_obj_set_style_text_color(ui_ActionLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ActionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActionLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionValue = lv_label_create(ui_ActionPanel);
    lv_obj_set_width(ui_ActionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ActionValue, 10);
    lv_obj_set_y(ui_ActionValue, 5);
    lv_label_set_text(ui_ActionValue, "Follow-Up");
    lv_obj_set_style_text_color(ui_ActionValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ActionValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActionValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionImage = lv_image_create(ui_ActionPanel);
    lv_image_set_src(ui_ActionImage, &ui_img_actionimage_png);
    lv_obj_set_width(ui_ActionImage, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_ActionImage, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_ActionImage, -15);
    lv_obj_set_y(ui_ActionImage, 3);
    lv_obj_set_align(ui_ActionImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ActionImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ActionImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SentimentPanel = lv_obj_create(ui_Email);
    lv_obj_remove_style_all(ui_SentimentPanel);
    lv_obj_set_width(ui_SentimentPanel, 95);
    lv_obj_set_height(ui_SentimentPanel, 52);
    lv_obj_set_x(ui_SentimentPanel, 19);
    lv_obj_set_y(ui_SentimentPanel, 56);
    lv_obj_set_align(ui_SentimentPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SentimentPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SentimentPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SentimentPanel, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SentimentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SentimentLabel = lv_label_create(ui_SentimentPanel);
    lv_obj_set_width(ui_SentimentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SentimentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SentimentLabel, 10);
    lv_obj_set_y(ui_SentimentLabel, -5);
    lv_obj_set_align(ui_SentimentLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_SentimentLabel, "Sentiment");
    lv_obj_set_style_text_color(ui_SentimentLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SentimentLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SentimentLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SentimentValue = lv_label_create(ui_SentimentPanel);
    lv_obj_set_width(ui_SentimentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SentimentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SentimentValue, 10);
    lv_obj_set_y(ui_SentimentValue, 5);
    lv_label_set_text(ui_SentimentValue, "Frastrated");
    lv_obj_set_style_text_color(ui_SentimentValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SentimentValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SentimentValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SentimentImage = lv_image_create(ui_SentimentPanel);
    lv_image_set_src(ui_SentimentImage, &ui_img_sentimentimage_png);
    lv_obj_set_width(ui_SentimentImage, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_SentimentImage, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_SentimentImage, -15);
    lv_obj_set_y(ui_SentimentImage, 6);
    lv_obj_set_align(ui_SentimentImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_SentimentImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SentimentImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PriorityPanel = lv_obj_create(ui_Email);
    lv_obj_remove_style_all(ui_PriorityPanel);
    lv_obj_set_width(ui_PriorityPanel, 66);
    lv_obj_set_height(ui_PriorityPanel, 52);
    lv_obj_set_x(ui_PriorityPanel, 113);
    lv_obj_set_y(ui_PriorityPanel, 56);
    lv_obj_set_align(ui_PriorityPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PriorityPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PriorityPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PriorityPanel, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PriorityPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PriorityLabel = lv_label_create(ui_PriorityPanel);
    lv_obj_set_width(ui_PriorityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PriorityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PriorityLabel, 10);
    lv_obj_set_y(ui_PriorityLabel, -5);
    lv_obj_set_align(ui_PriorityLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_PriorityLabel, "Priority");
    lv_obj_set_style_text_color(ui_PriorityLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PriorityLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PriorityLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PriorityValue = lv_label_create(ui_PriorityPanel);
    lv_obj_set_width(ui_PriorityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PriorityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PriorityValue, 10);
    lv_obj_set_y(ui_PriorityValue, 5);
    lv_label_set_text(ui_PriorityValue, "8");
    lv_obj_set_style_text_color(ui_PriorityValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PriorityValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PriorityValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PriorityImage = lv_image_create(ui_PriorityPanel);
    lv_image_set_src(ui_PriorityImage, &ui_img_priorityimage_png);
    lv_obj_set_width(ui_PriorityImage, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_PriorityImage, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_PriorityImage, -5);
    lv_obj_set_y(ui_PriorityImage, -3);
    lv_obj_set_align(ui_PriorityImage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_PriorityImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PriorityImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSuggested = lv_label_create(ui_Email);
    lv_obj_set_width(ui_LabelSuggested, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSuggested, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSuggested, -83);
    lv_obj_set_y(ui_LabelSuggested, 206);
    lv_obj_set_align(ui_LabelSuggested, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_LabelSuggested, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelSuggested, "Suggested Response");
    lv_obj_set_style_text_color(ui_LabelSuggested, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSuggested, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSuggested, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Email);
    lv_obj_set_width(ui_Panel4, 300);
    lv_obj_set_height(ui_Panel4, 70);
    lv_obj_set_x(ui_Panel4, 1);
    lv_obj_set_y(ui_Panel4, 222);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Panel4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SuggestedResponse = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_SuggestedResponse, 290);
    lv_obj_set_height(ui_SuggestedResponse, 65);
    lv_obj_set_x(ui_SuggestedResponse, -2);
    lv_obj_set_y(ui_SuggestedResponse, 2);
    lv_obj_set_align(ui_SuggestedResponse, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SuggestedResponse,
                      "Thanks Manoj, I see the claims in the decrypted Jwt token but for some reason they are not mapped to the Principal, so this always fails.  \n\nAny idea why?\n\nYour response will be appreciated!\n\nFrom: Stephen Halter  ");
    lv_obj_set_style_text_color(ui_SuggestedResponse, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SuggestedResponse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SuggestedResponse, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SuggestedResponse, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
