// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Record_screen_init(void)
{
    ui_Record = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Record, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_Record);
    lv_image_set_src(ui_Image12, &ui_img_microphone_10307974_1_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 118
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 115
    lv_obj_set_x(ui_Image12, 10);
    lv_obj_set_y(ui_Image12, 0);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image12, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image12, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_Image12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_Image12, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Spinner1 = lv_spinner_create(ui_Record);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 130);
    lv_obj_set_height(ui_Spinner1, 130);
    lv_obj_set_x(ui_Spinner1, 10);
    lv_obj_set_y(ui_Spinner1, 0);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Wifi = lv_imagebutton_create(ui_Record);
    lv_imagebutton_set_src(ui_Wifi, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_2128174856, NULL);
    lv_imagebutton_set_src(ui_Wifi, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_button1_png, NULL);
    lv_imagebutton_set_src(ui_Wifi, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_Wifi, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_Wifi, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_Wifi, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_Wifi, 45);
    lv_obj_set_width(ui_Wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Wifi, -119);
    lv_obj_set_y(ui_Wifi, -76);
    lv_obj_set_align(ui_Wifi, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Wifi, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ServerConn = lv_imagebutton_create(ui_Record);
    lv_imagebutton_set_src(ui_ServerConn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1682388829, NULL);
    lv_imagebutton_set_src(ui_ServerConn, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_button2_png, NULL);
    lv_imagebutton_set_src(ui_ServerConn, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_ServerConn, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_ServerConn, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_ServerConn, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ServerConn, 45);
    lv_obj_set_width(ui_ServerConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ServerConn, -119);
    lv_obj_set_y(ui_ServerConn, 0);
    lv_obj_set_align(ui_ServerConn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ServerConn, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Settings = lv_button_create(ui_Record);
    lv_obj_set_width(ui_Settings, 50);
    lv_obj_set_height(ui_Settings, 50);
    lv_obj_set_x(ui_Settings, -121);
    lv_obj_set_y(ui_Settings, 76);
    lv_obj_set_align(ui_Settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Settings, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Settings, &ui_img_vector_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Settings, lv_color_hex(0x008397), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings, lv_color_hex(0x0A8386), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Settings, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_Image12, ui_event_Image12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
