// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_image_create(ui_Splash);
    lv_image_set_src(ui_logo, &ui_img_flexibility_12969792_1_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 86
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_logo, 117);
    lv_obj_set_y(ui_logo, 38);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dotp = lv_image_create(ui_Splash);
    lv_image_set_src(ui_dotp, &ui_img_ellipse_4_png);
    lv_obj_set_width(ui_dotp, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_dotp, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_dotp, 117);
    lv_obj_set_y(ui_dotp, 129);
    lv_obj_add_flag(ui_dotp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_dotp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dotg = lv_image_create(ui_Splash);
    lv_image_set_src(ui_dotg, &ui_img_ellipse_5_png);
    lv_obj_set_width(ui_dotg, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_dotg, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_dotg, 152);
    lv_obj_set_y(ui_dotg, 129);
    lv_obj_add_flag(ui_dotg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_dotg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dotb = lv_image_create(ui_Splash);
    lv_image_set_src(ui_dotb, &ui_img_ellipse_6_png);
    lv_obj_set_width(ui_dotb, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_dotb, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_dotb, 187);
    lv_obj_set_y(ui_dotb, 129);
    lv_obj_add_flag(ui_dotb, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_dotb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_text = lv_image_create(ui_Splash);
    lv_image_set_src(ui_text, &ui_img_workdot_png);
    lv_obj_set_width(ui_text, LV_SIZE_CONTENT);   /// 195
    lv_obj_set_height(ui_text, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_text, 65);
    lv_obj_set_y(ui_text, 158);
    lv_obj_add_flag(ui_text, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_text, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
